# -*- coding: utf-8 -*-
"""linear_rgression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qraGZ19i1NZ7BwhFRdtJGImtrb76jYrd
"""

import numpy as np

import matplotlib.pyplot as plt

from sklearn.metrics import explained_variance_score

import pandas as pd

import zipfile
from google.colab import drive

drive.mount('/content/drive/')

zip_ref = zipfile.ZipFile("/content/california_price.zip", 'r')
zip_ref.extractall()
zip_ref.close()

df = pd.read_csv('/content/housing.csv')

df



x = df["total_rooms"].values

x= x.reshape(-1,1)

y =df["population"].values

y=y.reshape(-1,1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
...     x, y, test_size=0.33, random_state=42)









from sklearn.linear_model import LinearRegression

new_model = LinearRegression()

new_model.fit(x, y)

c =new_model.predict(y)

print(c)

from sklearn.metrics import r2_score

explained_variance_score(y,c)

plt.scatter(x, y)
plt.plot(y, c)
plt.legend(['Predicted Line', 'Observed Line'])
plt.show()

plt.figure(figsize=(26,14))
plt.plot(c,'g',label="Future Predicted Population ratio in california per area. Keep in mind this dataset was from the 90s With a 70 percent variance score.")
plt.plot(y,'r',label="At the time Current population ratio to area in California.")
plt.legend(loc="upper left")
plt.xlabel('This data is not by year just areas all over california adn from a census. Unusual results though.')
plt.ylabel('Population')
plt.title('Predicted population increase')
plt.show()